import fs from "node:fs";
import path from "node:path";
import IndexSentimentClient, { type IndexSeries } from "./IndexSentimentClient";

export const dynamic = "force-static";

type Payload = { generated_at_utc?: string; indexes?: IndexSeries[] };

function readPayload(): Payload | null {
  const candidates = [
    path.resolve(process.cwd(), "public/data/v5/index_sentiment.json"),
    path.resolve(process.cwd(), "apps/web/public/data/v5/index_sentiment.json"),
    path.resolve(process.cwd(), "../../apps/web/public/data/v5/index_sentiment.json"),
  ];
  for (const candidate of candidates) {
    try {
      if (!fs.existsSync(candidate)) continue;
      return JSON.parse(fs.readFileSync(candidate, "utf8")) as Payload;
    } catch {}
  }
  return null;
}

export default function IndicesPage() {
  const payload = readPayload();
  const indexes = Array.isArray(payload?.indexes) ? payload.indexes : [];
  return <main className="space-y-8">
    <section><div className="eyebrow">Index intelligence</div><h1 className="page-title mt-2">Multi-index sentiment</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-neutral-400">Compare observed news sentiment across large-cap, mid-cap, small-cap, Composite 1500, and the broader U.S. company layer without turning missing company-days into neutral zero.</p>{payload?.generated_at_utc ? <div className="mt-3 text-xs text-neutral-600">Updated {payload.generated_at_utc.slice(0,16).replace("T"," ")} UTC</div> : null}</section>
    {indexes.length ? <IndexSentimentClient indexes={indexes}/> : <div className="card p-6 text-sm text-neutral-500">Multi-index sentiment is being generated by the company-history fulfillment pipeline.</div>}
  </main>;
}
