// apps/web/app/portfolio/page.tsx
import { loadPortfolio, loadTicker } from "../../lib/data";
import PortfolioClient from "./PortfolioClient";

export const dynamic = "error";       // SSG
export const revalidate = false;

export default async function Page() {
  // Read static JSON generated by the pipeline
  const [portfolio, spy, spx] = await Promise.all([
    loadPortfolio(),
    loadTicker("SPY"),
    loadTicker("^GSPC"),
  ]);

  const dates: string[] = portfolio?.dates ?? [];
  const sentiment: number[] = portfolio?.S ?? portfolio?.sentiment ?? [];

  // Overlay index price if available (prefer SPY over ^GSPC)
  const price: number[] | undefined =
    (spy?.price?.length ? spy.price : undefined) ??
    (spx?.price?.length ? spx.price : undefined);

  return (
    <PortfolioClient
      dates={dates}
      sentiment={sentiment}
      price={price}
    />
  );
}
