"use client";

import Link from "next/link";
import { LanguageToggle } from "./LanguageProvider";

const primary = [["/", "Market"], ["/companies", "Companies"], ["/sp500", "S&P 500"], ["/lab", "Research Lab"]] as const;
const intelligence = [["/screener", "Screener"], ["/events", "Events"], ["/attribution", "Attribution"]] as const;
const platform = [["/portfolio", "Portfolio"], ["/research", "Research"], ["/agent", "Agent"], ["/data", "Data"], ["/methodology", "Methodology"]] as const;

export default function GlobalNavV2() {
  return <header className="sticky top-0 z-[100] isolate border-b border-white/10 bg-neutral-950"><nav className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 md:px-6">
    <Link href="/" className="flex shrink-0 items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl border border-emerald-400/30 bg-emerald-400/10 text-sm font-black text-emerald-300">SI</span><span><span className="block text-sm font-semibold text-white">Sentiment Intelligence</span><span className="hidden text-[11px] text-neutral-500 sm:block">Market evidence, not market noise</span></span></Link>
    <div className="hidden items-center gap-2 lg:flex"><div className="flex items-center gap-1 rounded-xl border border-white/10 bg-white/[0.03] p-1 text-sm">{primary.map(([href,label]) => <Link key={href} href={href} className="rounded-lg px-3 py-2 text-neutral-400 transition hover:bg-white/[0.06] hover:text-white">{label}</Link>)}<details className="group relative"><summary className="cursor-pointer list-none rounded-lg px-3 py-2 text-neutral-400 hover:bg-white/[0.06] hover:text-white [&::-webkit-details-marker]:hidden">More <span className="text-[10px]">▾</span></summary><div className="absolute right-0 top-[calc(100%+12px)] z-[120] w-[520px] rounded-2xl border border-white/10 bg-neutral-950 p-3 shadow-[0_24px_80px_rgba(0,0,0,0.78)] ring-1 ring-black"><div className="grid grid-cols-2 gap-2"><div className="rounded-xl border border-white/[0.06] p-2"><div className="px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-neutral-600">Intelligence</div>{intelligence.map(([href,label]) => <Link key={href} href={href} className="block rounded-lg px-2 py-2.5 text-sm text-neutral-300 hover:bg-white/[0.06] hover:text-white">{label}</Link>)}</div><div className="rounded-xl border border-white/[0.06] p-2"><div className="px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-neutral-600">Research & platform</div>{platform.map(([href,label]) => <Link key={href} href={href} className="block rounded-lg px-2 py-2.5 text-sm text-neutral-300 hover:bg-white/[0.06] hover:text-white">{label}</Link>)}</div></div></div></details></div><LanguageToggle /><Link href="/ask" className="rounded-xl border border-emerald-400/30 bg-emerald-400/10 px-4 py-2.5 text-sm font-semibold text-emerald-300">Ask</Link></div>
    <div className="flex items-center gap-2 lg:hidden"><LanguageToggle /><Link href="/ask" className="rounded-xl border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-xs font-semibold text-emerald-300">Ask</Link><details className="relative"><summary className="cursor-pointer list-none rounded-xl border border-white/10 bg-white/[0.03] px-3 py-2 text-xs text-neutral-300 [&::-webkit-details-marker]:hidden">Explore ▾</summary><div className="absolute right-0 top-[calc(100%+12px)] z-[120] w-64 rounded-2xl border border-white/10 bg-neutral-950 p-2 shadow-[0_24px_80px_rgba(0,0,0,0.78)] ring-1 ring-black">{[...primary,...intelligence,...platform].map(([href,label]) => <Link key={href} href={href} className="block rounded-lg px-3 py-2.5 text-sm text-neutral-300 hover:bg-white/[0.06]">{label}</Link>)}</div></details></div>
  </nav></header>;
}
