name: Build Data & Deploy Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode: sample (AAPL) or full (S&P500)"
        required: true
        default: "sample"
        type: choice
        options: ["sample", "full"]
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  PYTHONPATH: src
  HF_HUB_DISABLE_TELEMETRY: "1"
  NEXT_PUBLIC_BASE_PATH: "/market-sentiment-web"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Python setup ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --no-cache-dir "torch==2.3.1" --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir feedparser requests yfinance pandas_datareader

      - name: Configure HF cache
        run: echo "HF_HOME=$RUNNER_TEMP/hf-home" >> "$GITHUB_ENV"

      - name: Set date range (last 365 days)
        run: |
          python - <<'PY'
          import os
          from datetime import datetime, timedelta, timezone
          start=(datetime.now(timezone.utc)-timedelta(days=365)).strftime('%Y-%m-%d')
          end=datetime.now(timezone.utc).strftime('%Y-%m-%d')
          with open(os.environ['GITHUB_ENV'],'a') as f:
              f.write(f"START={start}\nEND={end}\n")
          print("START", start, "END", end)
          PY

      - name: Select mode and universe
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data
          if [ "${{ inputs.mode || 'sample' }}" = "full" ]; then
            MODE="full"
            TICKER_CSV="data/sp500.csv"
          else
            MODE="sample"
            TICKER_CSV="data/sample_one.csv"
            printf "ticker\nAAPL\n" > "$TICKER_CSV"
          fi
          echo "MODE=$MODE" >> "$GITHUB_ENV"
          echo "TICKER_CSV=$TICKER_CSV" >> "$GITHUB_ENV"
          echo "Mode: $MODE | Universe: $TICKER_CSV"

      # ---------- Smoke tests (unchanged logic) ----------
      - name: Smoke test — AAPL news providers + FinBERT
        env:
          HF_HOME: ${{ env.HF_HOME }}
        run: |
          python - <<'PY'
          import pandas as pd
          import yfinance as yf
          from market_sentiment.news import fetch_news, _prov_yfinance, _prov_google_rss, _prov_yahoo_rss, _prov_nasdaq_rss
          try:
              from market_sentiment.finbert import FinBERT
          except Exception:
              FinBERT = None

          START="${{ env.START }}"; END="${{ env.END }}"

          print("== yfinance raw count ==")
          try:
              raw = yf.Ticker("AAPL").news or []
              print("yfinance.Ticker('AAPL').news:", len(raw))
              if raw:
                  print("first keys:", list(raw[0].keys())[:5])
          except Exception as e:
              print("yfinance error:", e)

          provs = [
            ("google_rss", _prov_google_rss),
            ("yahoo_rss",  _prov_yahoo_rss),
            ("nasdaq_rss", _prov_nasdaq_rss),
            ("yfinance",   _prov_yfinance),
          ]
          for name, fn in provs:
            try:
              df = fn("AAPL", START, END, "Apple Inc.", 300)
              days = 0 if df.empty else df["ts"].dt.date.nunique()
              print(f"{name:11s} rows:{len(df):5d} | days: {days}")
            except Exception as e:
              print(f"{name} error:", e)

          try:
            all_df = fetch_news("AAPL", START, END, "Apple Inc.", max_per_provider=300)
            days = 0 if all_df.empty else all_df["ts"].dt.date.nunique()
            print("fetch_news rows:", len(all_df))
            print("fetch_news coverage days:", days)
            if len(all_df):
              print(all_df[["ts","title"]].tail(3).to_string(index=False))
          except Exception as e:
            print("fetch_news error:", e)
            all_df = pd.DataFrame()

          if len(all_df) and FinBERT is not None:
            texts = all_df["text"].fillna(all_df["title"]).astype(str).tolist()[:16]
            try:
              fb = FinBERT()
              try:
                S = fb.score(texts, batch=16)
              except TypeError:
                S = fb.score(texts)
              s = pd.Series(S).astype(float)
              print("FinBERT sample:", s.round(4).tolist(), "mean:", float(s.mean()))
            except Exception as e:
              print("FinBERT error:", e)
          else:
            print("Skip FinBERT (no texts or FinBERT missing).")
          PY

      - name: Smoke test — AAPL prices
        run: |
          python - <<'PY'
          from market_sentiment.prices import fetch_prices_yf
          p = fetch_prices_yf("AAPL", "${{ env.START }}", "${{ env.END }}")
          print("AAPL prices rows:", len(p))
          if not p.empty:
              print(p.head(2).to_string(index=False))
              print(p.tail(2).to_string(index=False))
          PY

      - name: Build JSON data (prices + news)
        env:
          HF_HOME: ${{ env.HF_HOME }}
        run: |
          set -euo pipefail
          echo "Build JSON for $(wc -l < "$TICKER_CSV" | tr -d ' ') tickers | batch=16 cutoff_min=5 max_workers=8"
          python -m market_sentiment.cli.build_json \
            --universe "$TICKER_CSV" \
            --start "$START" --end "$END" \
            --out apps/web/public/data \
            --batch 16 \
            --cutoff-minutes 5 \
            --max-workers 8

      - name: Inspect generated data (AAPL)
        run: |
          set -e
          echo "== List data dir =="
          ls -lah apps/web/public/data
          python - <<'PY'
          import json, os
          base="apps/web/public/data"
          tfile=os.path.join(base,"ticker","AAPL.json")
          if os.path.exists(tfile):
              obj=json.load(open(tfile))
              S = obj.get("S") or obj.get("sentiment") or []
              nz=sum(1 for x in S if abs((x or 0))>1e-12)
              print("AAPL sentiment: len=",len(S)," non_zero=",nz," first=",S[0] if S else None," last=",S[-1] if S else None)
              print("AAPL news items:", len(obj.get("news") or []))
          else:
              print("AAPL.json not found")
          print("tickers listed:", len(json.load(open(os.path.join(base,"_tickers.json")))))
          PY

      # ---------- Node / Next ----------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache-dependency-path: |
            apps/web/package-lock.json

      - name: Install web deps
        working-directory: apps/web
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Build & Export static site
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
        run: |
          set -euo pipefail
          echo "==== next.config.cjs ===="
          cat next.config.cjs
          echo "==== Node/NPM ===="
          node -v
          npm -v

          # Force real export to apps/web/out
          npm run build:export

          # Add .nojekyll so _next/ files are served
          touch out/.nojekyll

          echo "==== Verify exported routes exist ===="
          test -f out/index.html
          test -f out/ticker/AAPL/index.html
          test -f out/earnings/AAPL/index.html

          echo "==== Tree of out/ (top) ===="
          find out -maxdepth 2 -type f | sort | sed 's#^#  #'

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
