name: Build Data & Deploy Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"  # Mondays 12:00 UTC

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
      HF_HOME: ${{ runner.temp }}/hf-home   # fresh HF cache each run
      HF_HUB_DISABLE_TELEMETRY: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Python ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --no-cache-dir "torch==2.3.1" --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir -r requirements.txt
          pip check

      - name: Sanity check Python deps
        run: |
          python -c "import sys; print('PY', sys.version)"
          python -c "import torch; print('torch', torch.__version__)"
          python -c "import transformers, tokenizers; print('transformers', transformers.__version__, 'tokenizers', tokenizers.__version__)"
          python -c "import pandas, yfinance, bs4, lxml; print('pandas', pandas.__version__)"

      - name: Set dates (last 365 days)
        run: |
          echo "START=$(date -u -d '365 days ago' +%F)" >> $GITHUB_ENV || echo "START=$(python - <<PY
          from datetime import datetime, timedelta
          print((datetime.utcnow() - timedelta(days=365)).strftime('%Y-%m-%d'))
          PY
          )" >> $GITHUB_ENV
          echo "END=$(date -u +%F)" >> $GITHUB_ENV
          echo "Using START=$START END=$END"

      - name: Build S&P 500 universe
        run: python -m market_sentiment.cli.build_universe --out data/sp500.csv

      - name: Sanity check package layout
        run: |
          echo "Listing src/market_sentiment:"
          ls -la src/market_sentiment
          echo "Listing src/market_sentiment/cli:"
          ls -la src/market_sentiment/cli

      - name: Build JSON (FinBERT + Yahoo News + SEC/EDGAR)
        env:
          HF_HOME: ${{ env.HF_HOME }}   # ensure subprocesses see it
        run: |
          python -m market_sentiment.cli.build_json \
            --universe data/sp500.csv \
            --start "$START" --end "$END" \
            --out apps/web/public/data \
            --batch 16 \
            --limit 200

      # ---------- Web ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install web deps
        working-directory: apps/web
        run: npm install --no-audit --no-fund

      - name: "Build static site (Next.js output: export)"
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          NEXT_PUBLIC_BASE_PATH: "/market-sentiment-web"
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
