name: Build Data & Deploy Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode: sample (AAPL) or full (S&P500)"
        required: true
        default: "sample"
        type: choice
        options: ["sample", "full"]
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  PYTHONPATH: src
  HF_HUB_DISABLE_TELEMETRY: "1"
  NEXT_PUBLIC_BASE_PATH: "/market-sentiment-web"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --no-cache-dir "torch==2.3.1" --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir feedparser requests yfinance pandas_datareader

      - name: Configure HF cache
        run: echo "HF_HOME=$RUNNER_TEMP/hf-home" >> "$GITHUB_ENV"

      - name: Set date range (last 365 days)
        run: |
          python - <<'PY'
          import os
          from datetime import datetime, timedelta, timezone
          start=(datetime.now(timezone.utc)-timedelta(days=365)).strftime('%Y-%m-%d')
          end=datetime.now(timezone.utc).strftime('%Y-%m-%d')
          with open(os.environ['GITHUB_ENV'],'a') as f:
              f.write(f"START={start}\nEND={end}\n")
          print("START", start, "END", end)
          PY

      - name: Select mode and universe
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data
          if [ "${{ inputs.mode }}" = "full" ]; then
            MODE="full"
            TICKER_CSV="data/sp500.csv"
          else
            MODE="sample"
            TICKER_CSV="data/sample_one.csv"
            printf "ticker\nAAPL\n" > "$TICKER_CSV"
          fi
          echo "MODE=$MODE" >> "$GITHUB_ENV"
          echo "TICKER_CSV=$TICKER_CSV" >> "$GITHUB_ENV"
          echo "Mode: $MODE | Universe: $TICKER_CSV"

      - name: Smoke test — AAPL news (providers + coverage) + FinBERT
        env:
          HF_HOME: ${{ env.HF_HOME }}
        run: |
          python - <<'PY'
          import pandas as pd
          import yfinance as yf
          from market_sentiment.news import (
              _prov_yfinance, _prov_google_rss, _prov_yahoo_rss, _prov_nasdaq_rss, fetch_news
          )
          try:
              from market_sentiment.finbert import FinBERT
          except Exception:
              FinBERT = None

          START="${{ env.START }}"; END="${{ env.END }}"
          def cov_days(df: pd.DataFrame) -> int:
              if df is None or df.empty: return 0
              return pd.to_datetime(df["ts"], utc=True, errors="coerce").dt.date.dropna().nunique()

          print("== yfinance raw count ==")
          try:
              raw = yf.Ticker("AAPL").news or []
              print("yfinance.Ticker('AAPL').news:", len(raw))
              if raw: print("first keys:", list(raw[0].keys())[:5])
          except Exception as e:
              print("yfinance error:", e)

          provs = [
              ("google_rss", _prov_google_rss),
              ("yahoo_rss",  _prov_yahoo_rss),
              ("nasdaq_rss", _prov_nasdaq_rss),
              ("yfinance",   _prov_yfinance),
          ]
          for name, fn in provs:
              try:
                  df = fn("AAPL", START, END, "Apple Inc.", 9999)
                  print(f"{name:12s} rows: {len(df):4d} | days: {cov_days(df)}")
              except Exception as e:
                  print(f"{name} error:", e)

          df_all = fetch_news("AAPL", START, END, "Apple Inc.", max_per_provider=9999)
          print("fetch_news rows:", len(df_all))
          print("fetch_news coverage days:", cov_days(df_all))
          if not df_all.empty:
              print(df_all[["ts","title"]].tail(3).to_string(index=False))

          if not df_all.empty and FinBERT:
              texts = df_all["text"].fillna(df_all["title"]).astype(str).tolist()[:16]
              fb = FinBERT()
              try:
                  scores = fb.score(texts, batch=16)
              except TypeError:
                  scores = fb.score(texts)
              s = pd.Series(scores, dtype=float)
              print("FinBERT sample:", [round(x,4) for x in s.tolist()], "mean:", round(float(s.mean()),6))
          else:
              print("Skip FinBERT (no texts or FinBERT missing).")
          PY

      - name: Smoke test — AAPL prices
        run: |
          python - <<'PY'
          from market_sentiment.prices import fetch_prices_yf
          p = fetch_prices_yf("AAPL", "${{ env.START }}", "${{ env.END }}")
          print("AAPL prices rows:", len(p))
          if not p.empty:
              print(p.head(2).to_string(index=False))
              print(p.tail(2).to_string(index=False))
          PY

      - name: Build JSON data (prices + news)
        env:
          HF_HOME: ${{ env.HF_HOME }}
        run: |
          set -euo pipefail
          echo "Build JSON for $(wc -l < "$TICKER_CSV" | tr -d ' ') tickers | batch=16 cutoff_min=5 max_workers=8"
          python -m market_sentiment.cli.build_json \
            --universe "$TICKER_CSV" \
            --start "$START" --end "$END" \
            --out apps/web/public/data \
            --batch 16 \
            --cutoff-minutes 5 \
            --max-workers 8

      - name: Inspect generated data (AAPL)
        run: |
          set -euo pipefail
          echo "== List data dir =="
          ls -lah apps/web/public/data
          python - <<'PY'
          import json, os, pandas as pd
          base="apps/web/public/data"
          tfile=os.path.join(base,"ticker","AAPL.json")
          if os.path.exists(tfile):
              obj=json.load(open(tfile))
              S = obj.get("S") or obj.get("sentiment") or []
              nz=sum(1 for x in S if abs(x or 0)>1e-12)
              print(f"AAPL sentiment: len= {len(S)}  non_zero= {nz}  first= {round(S[0],6) if S else None}  last= {round(S[-1],6) if S else None}")
              news=obj.get("news") or []
              print("AAPL news items saved (trimmed):", len(news))
              print("AAPL news_total (all fetched):", obj.get("news_total"))
              print("AAPL news_day_count (unique days with news):", obj.get("news_day_count"))
          else:
              print("AAPL.json not found")
          PY

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: apps/web/package-lock.json

      - name: Install web deps
        working-directory: apps/web
        run: npm ci --no-audit --no-fund

      - name: Build static site (export)
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
        run: |
          set -euo pipefail
          echo "==== next.config.cjs (contents) ===="
          cat next.config.cjs || true
          echo "==== Node/NPM ===="
          node -v
          npm -v
          echo "==== Building ===="
          npm run build
          echo "==== After build (ls) ===="
          ls -lah
          if [ ! -d out ]; then
            echo "No 'out/' after build; synthesizing from '.next'..."
            mkdir -p out/_next
            rsync -a .next/static out/_next/static || true
            find .next/server/app -maxdepth 4 -name 'index.html' -print0 | while IFS= read -r -d '' f; do
              d="${f%.html}"; d="${d#.next/server/app}"
              mkdir -p "out/$d"
              cp "$f" "out/$d/index.html" || true
            done
            mkdir -p out/data
            cp -r public/data/* out/data/ || true
            if [ ! -f out/index.html ] && [ -f .next/server/app/index.html ]; then
              cp .next/server/app/index.html out/index.html || true
            fi
          fi
          echo "==== Final out/ listing ===="
          ls -lah out

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
