name: Build Data & Deploy Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode: sample (AAPL only) or full (all tickers)"
        required: true
        default: "sample"
        type: choice
        options: ["sample", "full"]
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  PYTHONPATH: src
  HF_HUB_DISABLE_TELEMETRY: "1"
  NEXT_PUBLIC_BASE_PATH: "/market-sentiment-web"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          # Torch CPU
          pip install --no-cache-dir "torch==2.3.1" --index-url https://download.pytorch.org/whl/cpu
          # Project deps
          pip install --no-cache-dir -r requirements.txt
          # Free-news deps
          pip install --no-cache-dir feedparser requests yfinance

      - name: Configure HF cache directory
        run: echo "HF_HOME=$RUNNER_TEMP/hf-home" >> "$GITHUB_ENV"

      - name: Set date range (last 365 days)
        run: |
          python - <<'PY'
          import os
          from datetime import datetime, timedelta, timezone
          start=(datetime.now(timezone.utc)-timedelta(days=365)).strftime('%Y-%m-%d')
          end=datetime.now(timezone.utc).strftime('%Y-%m-%d')
          with open(os.environ['GITHUB_ENV'],'a') as f:
              f.write(f"START={start}\nEND={end}\n")
          print("START", start, "END", end)
          PY

      - name: Select mode and universe
        run: |
          if [ "${{ inputs.mode }}" = "full" ]; then
            echo "MODE=full" >> "$GITHUB_ENV"
            echo "TICKER_CSV=data/sp500.csv" >> "$GITHUB_ENV"
          else
            echo "MODE=sample" >> "$GITHUB_ENV"
            echo "TICKER_CSV=data/sample_one.csv" >> "$GITHUB_ENV"
            printf "symbol\nAAPL\n" > data/sample_one.csv
          fi
          echo "Mode: ${MODE:-sample} | Universe: ${TICKER_CSV}"

      - name: News and FinBERT smoke test (AAPL)
        env:
          HF_HOME: ${{ env.HF_HOME }}
        run: |
          python - <<'PY'
          import pandas as pd
          import yfinance as yf
          from market_sentiment.news import fetch_news
          try:
              from market_sentiment.finbert import FinBERT
          except Exception:
              FinBERT = None

          START="${{ env.START }}"
          END="${{ env.END }}"

          print("== yfinance AAPL raw news count ==")
          try:
              raw = yf.Ticker("AAPL").news or []
              print(len(raw))
          except Exception as e:
              print("yfinance error:", e)

          print("== Multi-source fetch_news(AAPL) count ==")
          try:
              df = fetch_news("AAPL", START, END, company="Apple Inc.", max_per_provider=30, max_workers=6)
              print("rows:", len(df))
              if len(df):
                  print(df[["ts","title"]].tail(3).to_string(index=False))
          except Exception as e:
              print("fetch_news error:", e)
              df = pd.DataFrame()

          if len(df) > 0 and FinBERT is not None:
              texts = df["text"].fillna(df["title"]).astype(str).tolist()[:8]
              try:
                  fb = FinBERT()
                  try:
                      S = fb.score(texts, batch=8)   # if supported
                  except TypeError:
                      S = fb.score(texts)            # fallback
                  s = pd.Series(S).astype(float)
                  print("FinBERT S sample:", s.round(4).tolist())
                  print("S mean:", float(s.mean()), "nonzero:", int((s.abs() > 1e-12).sum()))
              except Exception as e:
                  print("FinBERT error:", e)
          else:
              print("Skip FinBERT (no texts or FinBERT missing).")
          PY

      - name: Build JSON data (prices + news + earnings)
        env:
          HF_HOME: ${{ env.HF_HOME }}
        run: |
          set -euxo pipefail
          python -m market_sentiment.cli.build_json \
            --universe "$TICKER_CSV" \
            --start "$START" --end "$END" \
            --out apps/web/public/data \
            --batch 16 \
            --cutoff-minutes 5 \
            --max-workers 8

      - name: Inspect generated data (AAPL)
        run: |
          set -e
          echo "== List data dir =="
          ls -lah apps/web/public/data
          python - <<'PY'
          import json, os
          base="apps/web/public/data"
          j=os.path.join(base,"ticker","AAPL.json")
          if os.path.exists(j):
              obj=json.load(open(j))
              S=obj.get("S") or obj.get("sentiment") or []
              nz=sum(1 for x in S if abs(x or 0)>1e-12)
              print("AAPL sentiment: len=",len(S)," non_zero=",nz," first=",S[0] if S else None," last=",S[-1] if S else None)
              print("AAPL news items:", len(obj.get("news") or []))
          else:
              print("AAPL.json not found")
          PY

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install web dependencies
        working-directory: apps/web
        run: npm install --no-audit --no-fund

      - name: Build static site
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
        run: |
          set -euxo pipefail
          echo "==== next.config.cjs (contents) ===="
          cat next.config.cjs || true
          echo "==== Node/NPM ===="
          node -v
          npm -v
          echo "==== Building ===="
          npm run build
          echo "==== After build (ls) ===="
          ls -lah
          if [ ! -d out ]; then
            echo "No 'out/' after build; synthesizing from '.next'..."
            mkdir -p out
            rsync -a .next/static out/_next/static || true
            # copy app route HTML where available
            find .next/server/app -maxdepth 3 -name 'index.html' -print0 | while IFS= read -r -d '' f; do
              d="${f%.html}"
              d="${d#.next/server/app}"
              mkdir -p "out/$d"
              cp "$f" "out/$d/index.html" || true
            done
            # ship data
            mkdir -p out/data
            cp -r public/data/* out/data/ || true
            # fallback root index
            if [ ! -f out/index.html ] && [ -f .next/server/app/index.html ]; then
              cp .next/server/app/index.html out/index.html || true
            fi
          fi
          echo "==== Final out/ listing ===="
          ls -lah out

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
