name: Build Data & Deploy Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode: sample (AAPL) or full (S&P500)"
        required: true
        default: "sample"
        type: choice
        options: ["sample", "full"]
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  PYTHONPATH: src
  HF_HUB_DISABLE_TELEMETRY: "1"
  NEXT_PUBLIC_BASE_PATH: "/market-sentiment-web"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Python & deps ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install --no-cache-dir "torch==2.3.1" --index-url https://download.pytorch.org/whl/cpu
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir feedparser requests yfinance pandas_datareader lxml html5lib

      - name: Configure HF cache
        run: echo "HF_HOME=$RUNNER_TEMP/hf-home" >> "$GITHUB_ENV"

      - name: Set date range (last 365 days)
        shell: python
        run: |
          import os
          from datetime import datetime, timedelta, timezone
          start=(datetime.now(timezone.utc)-timedelta(days=365)).strftime('%Y-%m-%d')
          end=datetime.now(timezone.utc).strftime('%Y-%m-%d')
          with open(os.environ['GITHUB_ENV'],'a') as f:
              f.write(f"START={start}\nEND={end}\n")
          print("START", start, "END", end)

      - name: Select mode and universe
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data
          MODE="${{ github.event.inputs.mode }}"
          if [ -z "${MODE:-}" ]; then MODE="sample"; fi
          if [ "$MODE" = "full" ]; then
            TICKER_CSV="data/sp500.csv"
          else
            TICKER_CSV="data/sample_one.csv"
            printf "ticker\nAAPL\n" > "$TICKER_CSV"
          fi
          echo "MODE=$MODE" >> "$GITHUB_ENV"
          echo "TICKER_CSV=$TICKER_CSV" >> "$GITHUB_ENV"
          echo "Mode: $MODE | Universe: $TICKER_CSV"

      - name: Generate S&P500 CSV if needed (MODE=full; multi-source, 403-safe)
        if: env.MODE == 'full'
        shell: python
        run: |
          import os, sys, pandas as pd, requests
          from pathlib import Path

          outp = Path("data/sp500.csv")
          if outp.exists() and outp.stat().st_size > 0:
              print(f"{outp} already exists; skipping fetch.")
              sys.exit(0)

          UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Safari/537.36"}
          candidates = []

          # 1) Wikipedia via requests (avoid 403 on pandas' internal opener)
          try:
              print("Trying Wikipedia…")
              r = requests.get("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies", headers=UA, timeout=30)
              r.raise_for_status()
              tables = pd.read_html(r.text)
              df = next((t for t in tables if "Symbol" in t.columns), None)
              if df is not None:
                  s = df["Symbol"].astype(str)
                  candidates.append(s)
                  print(f"Wikipedia ok: {len(s)} symbols")
              else:
                  print("Wikipedia: table with 'Symbol' not found")
          except Exception as e:
              print("Wikipedia failed:", e)

          # 2) Slickcharts (also HTML with a Symbol column)
          try:
              print("Trying Slickcharts…")
              r = requests.get("https://www.slickcharts.com/sp500", headers=UA, timeout=30)
              r.raise_for_status()
              tables = pd.read_html(r.text)
              df = next((t for t in tables if "Symbol" in t.columns), None)
              if df is None and len(tables):
                  # some mirrors give the table as first one
                  df = tables[0]
              if df is not None:
                  col = "Symbol" if "Symbol" in df.columns else df.columns[0]
                  s = df[col].astype(str)
                  candidates.append(s)
                  print(f"Slickcharts ok: {len(s)} symbols")
              else:
                  print("Slickcharts: table not found")
          except Exception as e:
              print("Slickcharts failed:", e)

          # 3) GitHub dataset (CSV)
          for url in [
              "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv",
              "https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv",
          ]:
              try:
                  print(f"Trying dataset: {url}")
                  df = pd.read_csv(url)
                  col = "Symbol" if "Symbol" in df.columns else ("symbol" if "symbol" in df.columns else None)
                  if col:
                      s = df[col].astype(str)
                      candidates.append(s)
                      print(f"Dataset ok: {len(s)} symbols from {url}")
                      break
                  else:
                      print(f"Dataset at {url}: no Symbol/symbol column")
              except Exception as e:
                  print(f"Dataset failed ({url}):", e)

          if not candidates:
              raise RuntimeError("All S&P500 sources failed (403/parse). Commit data/sp500.csv to repo to bypass network.")

          ser = pd.concat(candidates, ignore_index=True)
          ser = (ser.str.upper()
                     .str.replace(".", "-", regex=False)
                     .str.strip())
          uniq = sorted(set(x for x in ser if x))
          outp.parent.mkdir(parents=True, exist_ok=True)
          outp.write_text("ticker\n" + "\n".join(uniq) + "\n", encoding="utf-8")
          print(f"Wrote {len(uniq)} tickers to {outp}")

      # ---------- Smoke tests (debug news & prices) ----------
      - name: Smoke test — AAPL news providers + FinBERT
        env:
          HF_HOME: ${{ env.HF_HOME }}
        shell: python
        run: |
          import pandas as pd
          import yfinance as yf
          from market_sentiment.news import (
              _prov_yfinance, _prov_google_rss, _prov_yahoo_rss, _prov_nasdaq_rss, fetch_news
          )
          try:
              from market_sentiment.finbert import FinBERT
          except Exception:
              FinBERT = None

          START="${{ env.START }}"; END="${{ env.END }}"

          print("== yfinance raw count ==")
          try:
              raw = yf.Ticker("AAPL").news or []
              print("yfinance.Ticker('AAPL').news:", len(raw))
              if raw:
                  print("first keys:", list(raw[0].keys())[:5])
          except Exception as e:
              print("yfinance error:", e)

          providers = [
              ("google_rss", _prov_google_rss),
              ("yahoo_rss", _prov_yahoo_rss),
              ("nasdaq_rss", _prov_nasdaq_rss),
              ("yfinance", _prov_yfinance),
          ]
          for name, fn in providers:
              try:
                  df = fn("AAPL", START, END, "Apple Inc.", 300)
                  days = 0 if df.empty else df["ts"].dt.date.nunique()
                  print(f"{name:10s} rows:{len(df):5d} | days: {days}")
              except Exception as e:
                  print(f"{name} error:", e)

          try:
              all_df = fetch_news("AAPL", START, END, "Apple Inc.", max_per_provider=300)
              days = 0 if all_df.empty else all_df["ts"].dt.date.nunique()
              print("fetch_news rows:", len(all_df))
              print("fetch_news coverage days:", days)
              if len(all_df):
                  print(all_df[["ts","title"]].tail(3).to_string(index=False))
          except Exception as e:
              print("fetch_news error:", e)
              all_df = pd.DataFrame()

          if len(all_df) and FinBERT is not None:
              texts = all_df["text"].fillna(all_df["title"]).astype(str).tolist()[:16]
              try:
                  fb = FinBERT()
                  try:
                      S = fb.score(texts, batch=16)
                  except TypeError:
                      S = fb.score(texts)
                  s = pd.Series(S).astype(float)
                  print("FinBERT sample:", s.round(4).tolist(), "mean:", float(s.mean()))
              except Exception as e:
                  print("FinBERT error:", e)
          else:
              print("Skip FinBERT (no texts or FinBERT missing).")

      - name: Smoke test — AAPL prices
        shell: python
        run: |
          from market_sentiment.prices import fetch_prices_yf
          p = fetch_prices_yf("AAPL", "${{ env.START }}", "${{ env.END }}")
          print("AAPL prices rows:", len(p))
          if not p.empty:
              print(p.head(2).to_string(index=False))
              print(p.tail(2).to_string(index=False))

      # ---------- Build JSON data ----------
      - name: Build JSON data (prices + news)
        env:
          HF_HOME: ${{ env.HF_HOME }}
        shell: bash
        run: |
          set -euo pipefail
          echo "Build JSON for $(wc -l < "$TICKER_CSV" | tr -d ' ') tickers | batch=16 cutoff_min=5 max_workers=8"
          python -m market_sentiment.cli.build_json \
            --universe "$TICKER_CSV" \
            --start "$START" --end "$END" \
            --out apps/web/public/data \
            --batch 16 \
            --cutoff-minutes 5 \
            --max-workers 8

      - name: Inspect generated data (AAPL)
        shell: python
        run: |
          import json, os
          base="apps/web/public/data"
          print("== List data dir ==")
          for root, dirs, files in os.walk(base):
              for f in sorted(files):
                  p=os.path.join(root,f)
                  print(p)

          tfile=os.path.join(base,"ticker","AAPL.json")
          if os.path.exists(tfile):
              obj=json.load(open(tfile))
              S = obj.get("S") or obj.get("sentiment") or []
              nz=sum(1 for x in S if abs((x or 0))>1e-12)
              print(f"AAPL sentiment: len= {len(S)}  non_zero= {nz}  first= {S[0] if S else None}  last= {S[-1] if S else None}")
              news = obj.get("news") or []
              print("AAPL news items saved (trimmed):", len(news))
              days = len({ (n.get('ts') or '')[:10] for n in news if n.get('ts') })
              print("AAPL news_day_count (unique days with news):", days)
          else:
              print("AAPL.json not found")
          tickers = json.load(open(os.path.join(base,"_tickers.json")))
          print("tickers listed:", len(tickers))

      # ---------- Node & web build ----------
      - name: Setup Node.js (with npm cache)
        if: ${{ hashFiles('apps/web/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: apps/web/package-lock.json

      - name: Setup Node.js (no cache)
        if: ${{ hashFiles('apps/web/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install web deps (ci if lockfile, else install)
        working-directory: apps/web
        shell: bash
        run: |
          set -euo pipefail
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
          npm i -D @types/react @types/node --no-audit --no-fund || true

      - name: Build static site (create out/ from .next)
        working-directory: apps/web
        env:
          NEXT_TELEMETRY_DISABLED: "1"
          NEXT_PUBLIC_BASE_PATH: ${{ env.NEXT_PUBLIC_BASE_PATH }}
        shell: bash
        run: |
          set -euo pipefail
          echo "==== next.config.cjs ===="
          cat next.config.cjs || true
          echo "==== Node/NPM ===="
          node -v
          npm -v

          npm run build

          echo "==== Prepare out/ ===="
          if [ -d "out" ]; then
            echo "Next produced out/ already. Using it."
          else
            echo "No out/ from Next; synthesizing from .next artifacts..."
            rm -rf out
            mkdir -p out

            # Copy static assets
            if [ -d ".next/static" ]; then
              mkdir -p out/_next
              rsync -a .next/static out/_next/static
            fi

            # Copy public assets (includes /data/**)
            rsync -a public/ out/

            # Copy App Router HTML to route-style folders
            if [ -d ".next/server/app" ]; then
              find .next/server/app -type f -name 'index.html' -print0 | while IFS= read -r -d '' f; do
                rel="${f#.next/server/app}"
                dir="${rel%/index.html}"
                mkdir -p "out/${dir}"
                cp "$f" "out/${dir}/index.html"
              done
              find .next/server/app -type f -name '*.html' ! -name 'index.html' -print0 | while IFS= read -r -d '' f; do
                rel="${f#.next/server/app/}"
                rel_noext="${rel%.html}"
                mkdir -p "out/${rel_noext}"
                cp "$f" "out/${rel_noext}/index.html"
              done
            fi

            # 404 fallback for GH Pages
            if [ -f ".next/server/app/_not-found.html" ]; then
              cp ".next/server/app/_not-found.html" "out/404.html" || true
            elif [ ! -f "out/404.html" ] && [ -f "out/index.html" ]; then
              cp "out/index.html" "out/404.html" || true
            fi
          fi

          touch out/.nojekyll

          echo "==== Final out/ listing ===="
          find out -maxdepth 3 -type f | sort

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
